API META v1

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -172,12 +172,25 @@ jobs:
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: us-east-2
 
-      - name: Associate secondary layer to Lambda function
+      - name: Associate secondary layer to Lambda function with retries
         run: |
-          LAYER_SECONDARY_ARN=$(aws lambda list-layer-versions --layer-name anunc-ia-dependencies-secondary --query 'LayerVersions[-1].LayerVersionArn' --output text)
-          aws lambda update-function-configuration \
-            --function-name anunc-ia-backend \
-            --layers $LAYER_MAIN_ARN $LAYER_SECONDARY_ARN
+          MAX_RETRIES=5
+          RETRY_DELAY=10
+          for i in $(seq 1 $MAX_RETRIES); do
+            LAYER_SECONDARY_ARN=$(aws lambda list-layer-versions --layer-name anunc-ia-dependencies-secondary --query 'LayerVersions[-1].LayerVersionArn' --output text)
+            if aws lambda update-function-configuration --function-name anunc-ia-backend --layers $LAYER_MAIN_ARN $LAYER_SECONDARY_ARN; then
+              echo "Function configuration updated successfully."
+              break
+            else
+              echo "Update failed. Attempt $i of $MAX_RETRIES."
+              if [ $i -eq $MAX_RETRIES ]; then
+                echo "Max retries reached. Exiting with failure."
+                exit 1
+              fi
+              echo "Waiting for $RETRY_DELAY seconds before retrying..."
+              sleep $RETRY_DELAY
+            fi
+          done
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
