API META v1

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -6,113 +6,148 @@ on:
       - main
 
 jobs:
+  build_layer:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.10'
+
+      - name: Install dependencies for layer
+        run: |
+          mkdir -p python
+          pip install --no-cache-dir -r backend/requirements.txt -t python/
+
+      - name: Package layer
+        run: zip -r dependencies_layer.zip python
+
+      - name: Publish layer
+        run: |
+          aws lambda publish-layer-version \
+            --layer-name anunc-ia-dependencies \
+            --zip-file fileb://dependencies_layer.zip \
+            --compatible-runtimes python3.10
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: us-east-2
+
   deploy_backend:
     runs-on: ubuntu-latest
+    needs: build_layer
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.10'
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.10'
 
-    - name: Configure AWS credentials
-      uses: aws-actions/configure-aws-credentials@v1
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: us-east-2
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-east-2
 
-    - name: Install dependencies and package code
-      working-directory: ./backend
-      run: |
-        rm -rf build
-        mkdir -p build
-        python -m pip install --upgrade pip
-        pip install --no-cache-dir -r requirements.txt -t build
+      - name: Install dependencies for code (solo desarrollo)
+        run: |
+          mkdir -p build
+          pip install --no-cache-dir -r requirements.txt --target build
 
-        # Eliminar dependencias innecesarias
-        pip uninstall -y pycountry || true
-        pip uninstall -y ddtrace || true
+      - name: Remove dependencies already in layer
+        run: |
+          # Lista de paquetes instalados en la capa
+          LAYER_PACKAGES=$(pip freeze -r backend/requirements.txt | awk -F '==' '{print $1}')
+          for pkg in $LAYER_PACKAGES; do
+            pip uninstall -y $pkg
+          done
 
-        # Sincronizar archivos excluyendo los innecesarios
-        rsync -av \
-          --exclude='tests' \
-          --exclude='*.pyc' \
-          --exclude='__pycache__' \
-          --exclude='*.log' \
-          --exclude='.git' \
-          --exclude='docs' \
-          --exclude='*.md' \
-          . build/
+      - name: Synchronize code excluding dependencies
+        run: |
+          rsync -av \
+            --exclude='tests' \
+            --exclude='*.pyc' \
+            --exclude='__pycache__' \
+            --exclude='*.log' \
+            --exclude='.git' \
+            --exclude='docs' \
+            --exclude='*.md' \
+            --exclude='requirements.txt' \
+            . build/
 
-        # Comprimir de manera eficiente
-        cd build
-        zip -r9 ../backend.zip . -x "*.pyc" -x "__pycache__/*" -x "*.log" -x "docs/*" -x "*.md"
-        cd ..
+      - name: Package code
+        run: |
+          cd build
+          zip -r9 ../backend.zip . -x "*.pyc" -x "__pycache__/*" -x "*.log" -x "docs/*" -x "*.md"
+          cd ..
+          ZIP_SIZE=$(du -b backend.zip | cut -f1)
+          echo "Backend package size: $ZIP_SIZE bytes"
+          if [ $ZIP_SIZE -gt 52428800 ]; then
+            echo "Backend package size exceeds 50 MB limit."
+            exit 1
+          fi
 
-        # Analizar el tamaño del paquete
-        ZIP_SIZE=$(du -b backend.zip | cut -f1)
-        echo "Backend package size: $ZIP_SIZE bytes"
-        if [ $ZIP_SIZE -gt 52428800 ]; then
-          echo "Backend package size exceeds 50 MB limit."
-          exit 1
-        fi
+      - name: Upload code to Lambda
+        run: |
+          aws lambda update-function-code \
+            --function-name anunc-ia-backend \
+            --zip-file fileb://backend.zip
 
-        # Subir el código a Lambda
-        aws lambda update-function-code \
-          --function-name anunc-ia-backend \
-          --zip-file fileb://backend.zip
-
-    - name: Update Lambda layers
-      run: |
-        aws lambda update-function-configuration \
-          --function-name anunc-ia-backend \
-          --layers arn:aws:lambda:us-east-2:588738604551:layer:anunc-ia-dependencies:9
-      env:
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_DEFAULT_REGION: us-east-2
+      - name: Associate layer to Lambda function
+        run: |
+          LAYER_ARN=$(aws lambda list-layer-versions --layer-name anunc-ia-dependencies --query 'LayerVersions[-1].LayerVersionArn' --output text)
+          aws lambda update-function-configuration \
+            --function-name anunc-ia-backend \
+            --layers $LAYER_ARN
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: us-east-2
 
   deploy_frontend_after_backend:
     runs-on: ubuntu-latest
     needs: deploy_backend
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v2
-      with:
-        node-version: '18'
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '18'
 
-    - name: Install frontend dependencies
-      run: |
-        cd frontend
-        npm install
+      - name: Install frontend dependencies
+        run: |
+          cd frontend
+          npm install
 
-    - name: Build frontend
-      run: |
-        cd frontend
-        npm run build
+      - name: Build frontend
+        run: |
+          cd frontend
+          npm run build
 
-    - name: Verify dist directory exists
-      run: |
-        if [ ! -d "frontend/dist" ]; then
-          echo "Error: Dist directory not found. Exiting."
-          exit 1
-        fi
+      - name: Verify dist directory exists
+        run: |
+          if [ ! -d "frontend/dist" ]; then
+            echo "Error: Dist directory not found. Exiting."
+            exit 1
+          fi
 
-    - name: Configure AWS credentials
-      uses: aws-actions/configure-aws-credentials@v1
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: us-east-2
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-east-2
 
-    - name: Deploy frontend to S3
-      run: |
-        aws s3 sync frontend/dist/ s3://anunc-ia-frontend --delete
+      - name: Deploy frontend to S3
+        run: |
+          aws s3 sync frontend/dist/ s3://anunc-ia-frontend --delete
